export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const SET_CURRENT_SCREAM = 'SET_CURRENT_SCREAM';
export const CLEAR_CURRENT_SCREAM = 'CLEAR_CURRENT_SCREAM';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_SCREAMS = 'SET_SCREAMS';
export const LOADING_DATA = 'LOADING_DATA';
export const LIKE_SCREAM = 'LIKE_SCREAM';
export const UNLIKE_SCREAM = 'UNLIKE_SCREAM';
export const DELETE_SCREAM = 'DELETE_SCREAM';
